### ISSUE TITLE
django-fly-postgres-template

### ISSUE THREAD

**Issue by turian** [tomwojcik/django-fly-sqlite-template#1]
Where is [django-fly-postgres-template](https://github.com/tomwojcik/django-fly-postgres-template), referenced [here](https://github.com/tomwojcik/django-fly.io-example-project)?

It's also referenced in your README.

**Comment by tomwojcik** [comment]
It's still private as this template is not ready. I wanted to add a link before making the other repository read only.

I'll let you know once I'm done.

**Comment by tomwojcik** [comment]
https://github.com/tomwojcik/django-fly-postgres-template is now public.
